apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: binius-cert
  namespace: binius
spec:
  secretName: binius-tls

  dnsNames:
    - keccak.binius.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer
